site_name: freeact-skills
site_description: Predefined skills for freeact agent system

repo_name: gradion-ai/freeact-skills
repo_url: https://github.com/gradion-ai/freeact-skills

copyright: Copyright &copy; 2024 Gradion AI

theme:
  name: material
  font:
    text: Fira
    code: Fira Code
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [freeact_skills]
          options:
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            merge_init_into_class: true
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: false
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - footnotes

nav:
  - User guide:
    - Overview: index.md
    - Installation: installation.md
